name: Release

on: [push]

jobs:
  check-tag:
    name: Ensure the event is tag push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/bin/filter@master
        with:
          args: 'tag v*'

  publish:
    name: Publish to npm
    needs: check-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: NODE_VERSION=$(cat .nvmrc)
      - uses: actions/setup-node@v1
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn lerna publish from-package -y
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
